foreach(required SOURCE_ROOT BUILD_ROOT TEST_OUTPUT CONFIGURATION VERSION)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "Missing package test input: ${required}")
    endif()
endforeach()
execute_process(
    COMMAND powershell.exe -NoProfile -File "${SOURCE_ROOT}/scripts/package-release.ps1"
        -BuildDirectory "${BUILD_ROOT}" -OutputDirectory "${TEST_OUTPUT}"
        -Configuration "${CONFIGURATION}" -Version "${VERSION}"
    RESULT_VARIABLE package_result OUTPUT_VARIABLE package_output ERROR_VARIABLE package_error
)
if(NOT package_result EQUAL 0)
    message(FATAL_ERROR "Packaging failed: ${package_output}\n${package_error}")
endif()
set(release_root "${TEST_OUTPUT}/SatsumaTestLab-${VERSION}-windows-x64")
file(READ "${release_root}/release-manifest.json" manifest)
string(JSON count LENGTH "${manifest}" files)
math(EXPR last "${count} - 1")
foreach(index RANGE 0 ${last})
    string(JSON relative GET "${manifest}" files ${index} path)
    string(JSON expected_hash GET "${manifest}" files ${index} sha256)
    string(JSON expected_size GET "${manifest}" files ${index} size_bytes)
    file(SHA256 "${release_root}/${relative}" actual_hash)
    file(SIZE "${release_root}/${relative}" actual_size)
    if(NOT actual_hash STREQUAL expected_hash OR NOT actual_size EQUAL expected_size)
        message(FATAL_ERROR "Manifest does not describe installed file: ${relative}")
    endif()
endforeach()
file(GLOB_RECURSE delivered_files LIST_DIRECTORIES FALSE "${release_root}/*")
foreach(delivered_file IN LISTS delivered_files)
    file(RELATIVE_PATH payload_path "${release_root}" "${delivered_file}")
    if(payload_path MATCHES "(^|/)tests/" OR
       payload_path MATCHES "(^|/)(SatsumaVmInstallRollbackProbe|SatsumaVMTestAgent|SatsumaTestFixture|probe|older|newer|same)\\.exe$" OR
       payload_path MATCHES "(^|/)(real_vmware_[^/]+\\.(ps1|py)|make_installer_fixtures\\.py|install-agent\\.ps1)$")
        message(FATAL_ERROR "Developer fixture or legacy installer script entered the release: ${delivered_file}")
    endif()
endforeach()
if(NOT EXISTS "${release_root}/docs/验收与测试边界.md")
    message(FATAL_ERROR "Release is missing the acceptance scope documentation")
endif()
list(LENGTH delivered_files delivered_count)
math(EXPR expected_count "${count} + 1")
if(NOT delivered_count EQUAL expected_count)
    message(FATAL_ERROR "Manifest does not cover every payload file")
endif()
execute_process(
    COMMAND "${release_root}/SatsumaGuestAgent-Install/SatsumaVM.exe" --version --json
    OUTPUT_VARIABLE guest_version COMMAND_ERROR_IS_FATAL ANY
)
foreach(field version build_number build_attempt git_commit)
    string(JSON manifest_value GET "${manifest}" ${field})
    string(JSON binary_value GET "${guest_version}" ${field})
    if(NOT manifest_value STREQUAL binary_value)
        message(FATAL_ERROR "Manifest build identity differs from the actual Guest binary: ${field}")
    endif()
endforeach()
file(GLOB_RECURSE guest_files LIST_DIRECTORIES FALSE "${release_root}/SatsumaGuestAgent-Install/*")
list(LENGTH guest_files guest_count)
if(NOT guest_count EQUAL 1 OR NOT guest_files MATCHES "/SatsumaVM\\.exe$")
    message(FATAL_ERROR "Guest delivery contains unexpected files")
endif()
