# Satsuma VM Agent 安装与启动脚本
param(
    [string]$SharedRoot = '\\vmware-host\Shared Folders\vm-share',
    [string]$InstallRoot = '',
    [string]$AgentFileName = 'SatsumaVM.exe',
    [string]$ConfigFileName = 'agent.json'
)

$ErrorActionPreference = 'Stop'

Write-Host 'This script was generated by AI.'

# 按 CommandLineToArgvW 规则引用提权进程参数
function ConvertTo-WindowsCommandLineArgument {
    param([string]$Value)

    if ($Value.Length -gt 0 -and $Value -notmatch '[\s"]') {
        return $Value
    }

    $builder = New-Object Text.StringBuilder
    [void]$builder.Append('"')
    $backslashCount = 0
    foreach ($character in $Value.ToCharArray()) {
        if ($character -eq '\') {
            $backslashCount++
            continue
        }
        if ($character -eq '"') {
            [void]$builder.Append(('\' * ($backslashCount * 2 + 1)))
            [void]$builder.Append('"')
        } else {
            [void]$builder.Append(('\' * $backslashCount))
            [void]$builder.Append($character)
        }
        $backslashCount = 0
    }
    [void]$builder.Append(('\' * ($backslashCount * 2)))
    [void]$builder.Append('"')
    return $builder.ToString()
}

# 返回当前 PowerShell 是否具有完整管理员令牌
function Test-Administrator {
    $identity = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = New-Object Security.Principal.WindowsPrincipal($identity)
    return $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

# 验证候选目录位于可写固定盘且保留至少 2 GiB 空间
function Test-StorageRootCandidate {
    param([string]$Path)

    try {
        $fullPath = [IO.Path]::GetFullPath($Path)
        $driveRoot = [IO.Path]::GetPathRoot($fullPath)
        if ([string]::IsNullOrWhiteSpace($driveRoot)) {
            return $false
        }
        $drive = New-Object IO.DriveInfo($driveRoot)
        if (-not $drive.IsReady -or $drive.DriveType -ne [IO.DriveType]::Fixed) {
            return $false
        }
        if ($drive.AvailableFreeSpace -lt 2GB) {
            return $false
        }
        New-Item -ItemType Directory -Force -Path $fullPath | Out-Null
        $probe = Join-Path $fullPath ('.write-probe-' + [Guid]::NewGuid().ToString('N'))
        [IO.File]::WriteAllText($probe, 'probe', (New-Object Text.UTF8Encoding($false)))
        Remove-Item -Force -LiteralPath $probe
        return $true
    } catch {
        return $false
    }
}

# 自动选择统一本地存储根，显式参数仅用于旧目录迁移
function Resolve-SatsumaStorageRoot {
    param([string]$RequestedRoot)

    if (-not [string]::IsNullOrWhiteSpace($RequestedRoot)) {
        if (-not (Test-StorageRootCandidate $RequestedRoot)) {
            throw 'InstallRoot 必须位于可写且空间充足的本机固定磁盘。'
        }
        return [IO.Path]::GetFullPath($RequestedRoot)
    }
    $preferred = 'D:\SatsumaTestLab'
    if (Test-StorageRootCandidate $preferred) {
        return $preferred
    }
    $fallback = Join-Path $env:ProgramData 'SatsumaTestLab'
    if (-not (Test-StorageRootCandidate $fallback)) {
        throw 'D 盘和 ProgramData 回退目录均不满足 Satsuma 本地存储要求。'
    }
    return [IO.Path]::GetFullPath($fallback)
}

# 保护 Agent 和工作根，普通 Users 不获得全局写权限
function Set-SatsumaProtectedAcl {
    param([string]$Path)

    $acl = New-Object Security.AccessControl.DirectorySecurity
    $inheritance = [Security.AccessControl.InheritanceFlags]'ContainerInherit, ObjectInherit'
    $propagation = [Security.AccessControl.PropagationFlags]::None
    $allow = [Security.AccessControl.AccessControlType]::Allow
    foreach ($identity in @('SYSTEM', 'BUILTIN\Administrators')) {
        $rule = New-Object Security.AccessControl.FileSystemAccessRule(
            $identity,
            [Security.AccessControl.FileSystemRights]::FullControl,
            $inheritance,
            $propagation,
            $allow)
        [void]$acl.AddAccessRule($rule)
    }
    $acl.SetAccessRuleProtection($true, $false)
    Set-Acl -LiteralPath $Path -AclObject $acl
}

# 等待固定 Service 进入目标状态
function Wait-SatsumaServiceStatus {
    param(
        [ServiceProcess.ServiceController]$Service,
        [ServiceProcess.ServiceControllerStatus]$Status,
        [int]$TimeoutSeconds
    )

    $Service.WaitForStatus($Status, [TimeSpan]::FromSeconds($TimeoutSeconds))
    $Service.Refresh()
    if ($Service.Status -ne $Status) {
        throw "SatsumaVM Service 未在 $TimeoutSeconds 秒内进入 $Status。"
    }
}

# 请求固定 Service 停止并进行有限等待
function Stop-SatsumaService {
    $service = Get-Service -Name 'SatsumaVM' -ErrorAction SilentlyContinue
    if ($null -eq $service -or $service.Status -eq 'Stopped') {
        return
    }

    Stop-Service -InputObject $service -ErrorAction Stop
    Wait-SatsumaServiceStatus $service `
        ([ServiceProcess.ServiceControllerStatus]::Stopped) `
        20
}

# 首次迁移时停止并删除旧 SYSTEM 计划任务
function Remove-LegacySatsumaTask {
    $taskPath = '\Satsuma\'
    $taskName = 'SatsumaVM Agent'
    $task = Get-ScheduledTask `
        -TaskPath $taskPath `
        -TaskName $taskName `
        -ErrorAction SilentlyContinue
    if ($null -eq $task) {
        return
    }

    try {
        if ($task.State -in @('Running', 'Queued')) {
            Stop-ScheduledTask -InputObject $task -ErrorAction Stop
            $deadline = [DateTime]::UtcNow.AddSeconds(15)
            do {
                Start-Sleep -Milliseconds 100
                $task = Get-ScheduledTask `
                    -TaskPath $taskPath `
                    -TaskName $taskName `
                    -ErrorAction SilentlyContinue
            } while (
                $null -ne $task -and
                $task.State -in @('Running', 'Queued') -and
                [DateTime]::UtcNow -lt $deadline)
            if ($null -ne $task -and $task.State -in @('Running', 'Queued')) {
                throw '旧 SatsumaVM 计划任务未在 15 秒内停止。'
            }
        }

        if ($null -ne $task) {
            Unregister-ScheduledTask `
                -TaskPath $taskPath `
                -TaskName $taskName `
                -Confirm:$false `
                -ErrorAction Stop
        }
    } catch {
        throw "迁移旧 SatsumaVM 计划任务失败：$($_.Exception.Message)"
    }
}

# 普通 PowerShell 启动时自动请求一次 UAC
if (-not (Test-Administrator)) {
    $powerShellPath = (Get-Process -Id $PID).Path
    $elevatedArguments = @(
        '-NoProfile',
        '-ExecutionPolicy', 'Bypass',
        '-File', $PSCommandPath,
        '-SharedRoot', $SharedRoot,
        '-InstallRoot', $InstallRoot,
        '-AgentFileName', $AgentFileName,
        '-ConfigFileName', $ConfigFileName
    )
    $argumentText = (
        $elevatedArguments |
            ForEach-Object { ConvertTo-WindowsCommandLineArgument ([string]$_) }
    ) -join ' '
    $process = Start-Process `
        -FilePath $powerShellPath `
        -ArgumentList $argumentText `
        -WorkingDirectory $PSScriptRoot `
        -Verb RunAs `
        -Wait `
        -PassThru
    exit $process.ExitCode
}

# 固定共享目录输入
$bootstrapRoot = Join-Path $SharedRoot 'satsuma-bootstrap'
$sourceAgent = Join-Path $bootstrapRoot $AgentFileName
$sourceConfig = Join-Path $bootstrapRoot $ConfigFileName
foreach ($sourceFile in @($sourceAgent, $sourceConfig)) {
    if (-not (Test-Path -LiteralPath $sourceFile -PathType Leaf)) {
        throw "缺少 Agent 安装文件：$sourceFile"
    }
}

# 统一本机安装布局
$InstallRoot = Resolve-SatsumaStorageRoot $InstallRoot
$agentRoot = Join-Path $InstallRoot 'agent'
$binRoot = Join-Path $agentRoot 'bin'
$workRoot = Join-Path $InstallRoot 'work'
$targetAgent = Join-Path $binRoot 'SatsumaVM.exe'
$newAgent = Join-Path $binRoot 'SatsumaVM.new.exe'
$backupAgent = Join-Path $binRoot 'SatsumaVM.bak.exe'
$targetConfig = Join-Path $agentRoot 'agent.json'
$newConfig = Join-Path $agentRoot 'agent.json.new'
$backupConfig = Join-Path $agentRoot 'agent.json.bak'
$targetScript = Join-Path $agentRoot 'install-agent.ps1'

# 防止两个管理员安装流程同时替换 Agent
$installMutex = New-Object Threading.Mutex($false, 'Global\SatsumaVM-Install')
$ownsInstallMutex = $false
$agentWasBackedUp = $false
$configWasBackedUp = $false
$installSucceeded = $false
try {
    try {
        $ownsInstallMutex = $installMutex.WaitOne([TimeSpan]::FromSeconds(30))
    } catch [Threading.AbandonedMutexException] {
        $ownsInstallMutex = $true
    }
    if (-not $ownsInstallMutex) {
        throw '另一个 SatsumaVM 安装正在运行。'
    }

    New-Item -ItemType Directory -Force -Path $InstallRoot, $agentRoot, $binRoot, $workRoot | Out-Null
    Set-SatsumaProtectedAcl $agentRoot
    Set-SatsumaProtectedAcl $workRoot
    Remove-Item -Force -LiteralPath `
        $newAgent, $backupAgent, $newConfig, $backupConfig `
        -ErrorAction SilentlyContinue

    # 在停止当前 Agent 前复制、校验并解析完整候选
    Copy-Item -Force -LiteralPath $sourceAgent -Destination $newAgent
    $candidateConfig = Get-Content -Raw -Encoding UTF8 -LiteralPath $sourceConfig | ConvertFrom-Json
    if ($candidateConfig.PSObject.Properties.Name -contains 'storage_root') {
        $candidateConfig.storage_root = $InstallRoot
    } else {
        $candidateConfig | Add-Member -NotePropertyName storage_root -NotePropertyValue $InstallRoot
    }
    $candidateConfig.local_work_root = $workRoot
    $configText = $candidateConfig | ConvertTo-Json -Depth 20
    [IO.File]::WriteAllText($newConfig, $configText + "`n", (New-Object Text.UTF8Encoding($false)))
    $sourceHash = (Get-FileHash -Algorithm SHA256 -LiteralPath $sourceAgent).Hash
    $candidateHash = (Get-FileHash -Algorithm SHA256 -LiteralPath $newAgent).Hash
    if ($sourceHash -cne $candidateHash) {
        throw 'SatsumaVM 候选复制后的 SHA-256 不一致。'
    }
    & $newAgent --config $newConfig --validate-config
    if ($LASTEXITCODE -ne 0) {
        throw "SatsumaVM 配置预检失败，退出码：$LASTEXITCODE"
    }

    Stop-SatsumaService
    Remove-LegacySatsumaTask

    # 只保留本次切换所需的一份简单备份
    if (Test-Path -LiteralPath $targetAgent -PathType Leaf) {
        Move-Item -LiteralPath $targetAgent -Destination $backupAgent
        $agentWasBackedUp = $true
    }
    if (Test-Path -LiteralPath $targetConfig -PathType Leaf) {
        Move-Item -LiteralPath $targetConfig -Destination $backupConfig
        $configWasBackedUp = $true
    }
    Move-Item -LiteralPath $newAgent -Destination $targetAgent
    Move-Item -LiteralPath $newConfig -Destination $targetConfig

    & $targetAgent --config $targetConfig --install-service
    if ($LASTEXITCODE -ne 0) {
        throw "SatsumaVM Service 安装失败，退出码：$LASTEXITCODE"
    }

    Copy-Item -Force -LiteralPath $PSCommandPath -Destination $targetScript
    $installSucceeded = $true
    Remove-Item -Force -LiteralPath `
        $backupAgent, $newAgent, $backupConfig, $newConfig `
        -ErrorAction SilentlyContinue

    # 显示刚安装的实际 Service 状态、命令行和 Agent 版本
    $installedService = Get-CimInstance `
        -ClassName Win32_Service `
        -Filter "Name='SatsumaVM'" `
        -ErrorAction Stop
    $installedVersion = (& $targetAgent --version | Out-String).Trim()
    if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($installedVersion)) {
        throw "无法读取已安装 SatsumaVM 版本，退出码：$LASTEXITCODE"
    }
    $isRunning = $installedService.State -eq 'Running'
    Write-Host 'SatsumaVM Service 安装结果：'
    Write-Host "  服务状态：$($installedService.State)"
    Write-Host "  启动类型：$($installedService.StartMode)"
    Write-Host "  正在运行：$isRunning"
    Write-Host "  服务命令：$($installedService.PathName)"
    Write-Host "  EXE 路径：$targetAgent"
    Write-Host "  Agent 版本：$installedVersion"
    Write-Host '安装和 Host check 验收完成后，请关闭 VM 电源并重新制作包含本 Service 的基础快照。'
} catch {
    $installError = $_
    if (-not $installSucceeded) {
        try {
            Stop-SatsumaService
        } catch {
            Write-Warning "停止失败候选 Service 时出错：$($_.Exception.Message)"
        }

        try {
            Remove-Item -Force -LiteralPath $targetAgent -ErrorAction SilentlyContinue
            if ($agentWasBackedUp -and (Test-Path -LiteralPath $backupAgent -PathType Leaf)) {
                Move-Item -LiteralPath $backupAgent -Destination $targetAgent
            }
            Remove-Item -Force -LiteralPath $targetConfig -ErrorAction SilentlyContinue
            if ($configWasBackedUp -and (Test-Path -LiteralPath $backupConfig -PathType Leaf)) {
                Move-Item -LiteralPath $backupConfig -Destination $targetConfig
            }
            if (
                $agentWasBackedUp -and
                $configWasBackedUp -and
                (Test-Path -LiteralPath $targetAgent -PathType Leaf) -and
                (Test-Path -LiteralPath $targetConfig -PathType Leaf)
            ) {
                & $targetAgent --config $targetConfig --install-service
                if ($LASTEXITCODE -ne 0) {
                    Write-Warning "恢复旧 SatsumaVM Service 失败，退出码：$LASTEXITCODE"
                }
            }
        } catch {
            Write-Warning "恢复旧 SatsumaVM 文件时出错：$($_.Exception.Message)"
        }
    }
    throw $installError
} finally {
    Remove-Item -Force -LiteralPath $newAgent, $newConfig -ErrorAction SilentlyContinue
    if ($ownsInstallMutex) {
        [void]$installMutex.ReleaseMutex()
    }
    $installMutex.Dispose()
}
