# Satsuma VM Agent 安装与启动脚本
param(
    [string]$SharedRoot = '\\vmware-host\Shared Folders\vm-share',
    [string]$InstallRoot = 'C:\Satsuma',
    [string]$AgentFileName = 'SatsumaVM.exe',
    [string]$ConfigFileName = 'agent.json'
)

$ErrorActionPreference = 'Stop'

Write-Host 'This script was generated by AI.'

# 按 CommandLineToArgvW 规则引用提权进程参数
function ConvertTo-WindowsCommandLineArgument {
    param([string]$Value)

    if ($Value.Length -gt 0 -and $Value -notmatch '[\s"]') {
        return $Value
    }

    $builder = New-Object Text.StringBuilder
    [void]$builder.Append('"')
    $backslashCount = 0
    foreach ($character in $Value.ToCharArray()) {
        if ($character -eq '\') {
            $backslashCount++
            continue
        }
        if ($character -eq '"') {
            [void]$builder.Append(('\' * ($backslashCount * 2 + 1)))
            [void]$builder.Append('"')
        } else {
            [void]$builder.Append(('\' * $backslashCount))
            [void]$builder.Append($character)
        }
        $backslashCount = 0
    }
    [void]$builder.Append(('\' * ($backslashCount * 2)))
    [void]$builder.Append('"')
    return $builder.ToString()
}

# 返回当前 PowerShell 是否具有完整管理员令牌
function Test-Administrator {
    $identity = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = New-Object Security.Principal.WindowsPrincipal($identity)
    return $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

# 等待固定 Service 进入目标状态
function Wait-SatsumaServiceStatus {
    param(
        [ServiceProcess.ServiceController]$Service,
        [ServiceProcess.ServiceControllerStatus]$Status,
        [int]$TimeoutSeconds
    )

    $Service.WaitForStatus($Status, [TimeSpan]::FromSeconds($TimeoutSeconds))
    $Service.Refresh()
    if ($Service.Status -ne $Status) {
        throw "SatsumaVM Service 未在 $TimeoutSeconds 秒内进入 $Status。"
    }
}

# 请求固定 Service 停止并进行有限等待
function Stop-SatsumaService {
    $service = Get-Service -Name 'SatsumaVM' -ErrorAction SilentlyContinue
    if ($null -eq $service -or $service.Status -eq 'Stopped') {
        return
    }

    Stop-Service -InputObject $service -ErrorAction Stop
    Wait-SatsumaServiceStatus $service `
        ([ServiceProcess.ServiceControllerStatus]::Stopped) `
        20
}

# 首次迁移时停止并删除旧 SYSTEM 计划任务
function Remove-LegacySatsumaTask {
    $taskPath = '\Satsuma\'
    $taskName = 'SatsumaVM Agent'
    $task = Get-ScheduledTask `
        -TaskPath $taskPath `
        -TaskName $taskName `
        -ErrorAction SilentlyContinue
    if ($null -eq $task) {
        return
    }

    try {
        if ($task.State -in @('Running', 'Queued')) {
            Stop-ScheduledTask -InputObject $task -ErrorAction Stop
            $deadline = [DateTime]::UtcNow.AddSeconds(15)
            do {
                Start-Sleep -Milliseconds 100
                $task = Get-ScheduledTask `
                    -TaskPath $taskPath `
                    -TaskName $taskName `
                    -ErrorAction SilentlyContinue
            } while (
                $null -ne $task -and
                $task.State -in @('Running', 'Queued') -and
                [DateTime]::UtcNow -lt $deadline)
            if ($null -ne $task -and $task.State -in @('Running', 'Queued')) {
                throw '旧 SatsumaVM 计划任务未在 15 秒内停止。'
            }
        }

        if ($null -ne $task) {
            Unregister-ScheduledTask `
                -TaskPath $taskPath `
                -TaskName $taskName `
                -Confirm:$false `
                -ErrorAction Stop
        }
    } catch {
        throw "迁移旧 SatsumaVM 计划任务失败：$($_.Exception.Message)"
    }
}

# 普通 PowerShell 启动时自动请求一次 UAC
if (-not (Test-Administrator)) {
    $powerShellPath = (Get-Process -Id $PID).Path
    $elevatedArguments = @(
        '-NoProfile',
        '-ExecutionPolicy', 'Bypass',
        '-File', $PSCommandPath,
        '-SharedRoot', $SharedRoot,
        '-InstallRoot', $InstallRoot,
        '-AgentFileName', $AgentFileName,
        '-ConfigFileName', $ConfigFileName
    )
    $argumentText = (
        $elevatedArguments |
            ForEach-Object { ConvertTo-WindowsCommandLineArgument ([string]$_) }
    ) -join ' '
    $process = Start-Process `
        -FilePath $powerShellPath `
        -ArgumentList $argumentText `
        -WorkingDirectory $PSScriptRoot `
        -Verb RunAs `
        -Wait `
        -PassThru
    exit $process.ExitCode
}

# 固定共享目录输入
$bootstrapRoot = Join-Path $SharedRoot 'satsuma-bootstrap'
$sourceAgent = Join-Path $bootstrapRoot $AgentFileName
$sourceConfig = Join-Path $bootstrapRoot $ConfigFileName
foreach ($sourceFile in @($sourceAgent, $sourceConfig)) {
    if (-not (Test-Path -LiteralPath $sourceFile -PathType Leaf)) {
        throw "缺少 Agent 安装文件：$sourceFile"
    }
}

# 固定本机安装布局
$InstallRoot = [IO.Path]::GetFullPath($InstallRoot)
$installDriveRoot = [IO.Path]::GetPathRoot($InstallRoot)
if ([string]::IsNullOrWhiteSpace($installDriveRoot)) {
    throw 'InstallRoot 必须位于本机固定磁盘。'
}
$installDrive = New-Object IO.DriveInfo($installDriveRoot)
if ($installDrive.DriveType -ne [IO.DriveType]::Fixed) {
    throw 'InstallRoot 必须位于本机固定磁盘，不能直接使用 VMware 共享目录。'
}

$binRoot = Join-Path $InstallRoot 'bin'
$workRoot = Join-Path $InstallRoot 'work'
$targetAgent = Join-Path $binRoot 'SatsumaVM.exe'
$newAgent = Join-Path $binRoot 'SatsumaVM.new.exe'
$backupAgent = Join-Path $binRoot 'SatsumaVM.bak.exe'
$targetConfig = Join-Path $InstallRoot 'agent.json'
$newConfig = Join-Path $InstallRoot 'agent.json.new'
$backupConfig = Join-Path $InstallRoot 'agent.json.bak'
$targetScript = Join-Path $InstallRoot 'install-agent.ps1'

# 防止两个管理员安装流程同时替换 Agent
$installMutex = New-Object Threading.Mutex($false, 'Global\SatsumaVM-Install')
$ownsInstallMutex = $false
$agentWasBackedUp = $false
$configWasBackedUp = $false
$installSucceeded = $false
try {
    try {
        $ownsInstallMutex = $installMutex.WaitOne([TimeSpan]::FromSeconds(30))
    } catch [Threading.AbandonedMutexException] {
        $ownsInstallMutex = $true
    }
    if (-not $ownsInstallMutex) {
        throw '另一个 SatsumaVM 安装正在运行。'
    }

    New-Item -ItemType Directory -Force -Path $InstallRoot, $binRoot, $workRoot | Out-Null
    Remove-Item -Force -LiteralPath `
        $newAgent, $backupAgent, $newConfig, $backupConfig `
        -ErrorAction SilentlyContinue

    # 在停止当前 Agent 前复制、校验并解析完整候选
    Copy-Item -Force -LiteralPath $sourceAgent -Destination $newAgent
    Copy-Item -Force -LiteralPath $sourceConfig -Destination $newConfig
    $sourceHash = (Get-FileHash -Algorithm SHA256 -LiteralPath $sourceAgent).Hash
    $candidateHash = (Get-FileHash -Algorithm SHA256 -LiteralPath $newAgent).Hash
    if ($sourceHash -cne $candidateHash) {
        throw 'SatsumaVM 候选复制后的 SHA-256 不一致。'
    }
    & $newAgent --config $newConfig --validate-config
    if ($LASTEXITCODE -ne 0) {
        throw "SatsumaVM 配置预检失败，退出码：$LASTEXITCODE"
    }

    Stop-SatsumaService
    Remove-LegacySatsumaTask

    # 只保留本次切换所需的一份简单备份
    if (Test-Path -LiteralPath $targetAgent -PathType Leaf) {
        Move-Item -LiteralPath $targetAgent -Destination $backupAgent
        $agentWasBackedUp = $true
    }
    if (Test-Path -LiteralPath $targetConfig -PathType Leaf) {
        Move-Item -LiteralPath $targetConfig -Destination $backupConfig
        $configWasBackedUp = $true
    }
    Move-Item -LiteralPath $newAgent -Destination $targetAgent
    Move-Item -LiteralPath $newConfig -Destination $targetConfig

    & $targetAgent --config $targetConfig --install-service
    if ($LASTEXITCODE -ne 0) {
        throw "SatsumaVM Service 安装失败，退出码：$LASTEXITCODE"
    }

    Copy-Item -Force -LiteralPath $PSCommandPath -Destination $targetScript
    $installSucceeded = $true
    Remove-Item -Force -LiteralPath `
        $backupAgent, $newAgent, $backupConfig, $newConfig `
        -ErrorAction SilentlyContinue
    Write-Host "SatsumaVM Service 已安装并启动：$targetAgent"
} catch {
    $installError = $_
    if (-not $installSucceeded) {
        try {
            Stop-SatsumaService
        } catch {
            Write-Warning "停止失败候选 Service 时出错：$($_.Exception.Message)"
        }

        try {
            Remove-Item -Force -LiteralPath $targetAgent -ErrorAction SilentlyContinue
            if ($agentWasBackedUp -and (Test-Path -LiteralPath $backupAgent -PathType Leaf)) {
                Move-Item -LiteralPath $backupAgent -Destination $targetAgent
            }
            Remove-Item -Force -LiteralPath $targetConfig -ErrorAction SilentlyContinue
            if ($configWasBackedUp -and (Test-Path -LiteralPath $backupConfig -PathType Leaf)) {
                Move-Item -LiteralPath $backupConfig -Destination $targetConfig
            }
            if (
                $agentWasBackedUp -and
                $configWasBackedUp -and
                (Test-Path -LiteralPath $targetAgent -PathType Leaf) -and
                (Test-Path -LiteralPath $targetConfig -PathType Leaf)
            ) {
                & $targetAgent --config $targetConfig --install-service
                if ($LASTEXITCODE -ne 0) {
                    Write-Warning "恢复旧 SatsumaVM Service 失败，退出码：$LASTEXITCODE"
                }
            }
        } catch {
            Write-Warning "恢复旧 SatsumaVM 文件时出错：$($_.Exception.Message)"
        }
    }
    throw $installError
} finally {
    Remove-Item -Force -LiteralPath $newAgent, $newConfig -ErrorAction SilentlyContinue
    if ($ownsInstallMutex) {
        [void]$installMutex.ReleaseMutex()
    }
    $installMutex.Dispose()
}
