# Satsuma VM Agent 安装与启动脚本

param(
    [string]$SharedRoot = '\\vmware-host\Shared Folders\vm-share',
    [string]$InstallRoot = 'C:\Satsuma',
    [string]$AgentFileName = 'SatsumaVM.exe',
    [string]$ConfigFileName = 'agent.json'
)

Write-Host 'This script was generated by AI.'

$ErrorActionPreference = 'Stop'

# 按 CommandLineToArgvW 规则引用提权进程参数
function ConvertTo-WindowsCommandLineArgument {
    param([string]$Value)

    if ($Value.Length -gt 0 -and $Value -notmatch '[\s"]') {
        return $Value
    }

    $builder = New-Object Text.StringBuilder
    [void]$builder.Append('"')
    $backslashCount = 0
    foreach ($character in $Value.ToCharArray()) {
        if ($character -eq [char]'\') {
            $backslashCount++
            continue
        }
        if ($character -eq [char]'"') {
            [void]$builder.Append([char]'\', ($backslashCount * 2) + 1)
            [void]$builder.Append('"')
            $backslashCount = 0
            continue
        }
        if ($backslashCount -gt 0) {
            [void]$builder.Append([char]'\', $backslashCount)
            $backslashCount = 0
        }
        [void]$builder.Append($character)
    }
    if ($backslashCount -gt 0) {
        [void]$builder.Append([char]'\', $backslashCount * 2)
    }
    [void]$builder.Append('"')
    return $builder.ToString()
}

# 返回当前 PowerShell 是否具有完整管理员令牌
function Test-Administrator {
    $currentIdentity = [Security.Principal.WindowsIdentity]::GetCurrent()
    $currentPrincipal = New-Object Security.Principal.WindowsPrincipal($currentIdentity)
    $administratorRole = [Security.Principal.WindowsBuiltInRole]::Administrator
    return $currentPrincipal.IsInRole($administratorRole)
}

# 普通 PowerShell 启动时自动请求一次 UAC，不要求用户预先打开管理员终端
if (-not (Test-Administrator)) {
    $powerShellPath = Join-Path $env:SystemRoot 'System32\WindowsPowerShell\v1.0\powershell.exe'
    $elevationArguments = @(
        '-NoProfile',
        '-ExecutionPolicy', 'Bypass',
        '-File', $PSCommandPath,
        '-SharedRoot', $SharedRoot,
        '-InstallRoot', $InstallRoot,
        '-AgentFileName', $AgentFileName,
        '-ConfigFileName', $ConfigFileName
    )
    $argumentText = ($elevationArguments | ForEach-Object {
        ConvertTo-WindowsCommandLineArgument $_
    }) -join ' '
    $elevatedProcess = Start-Process `
        -FilePath $powerShellPath `
        -ArgumentList $argumentText `
        -WorkingDirectory $env:SystemRoot `
        -Verb RunAs `
        -Wait `
        -PassThru
    exit $elevatedProcess.ExitCode
}

# 返回从固定安装路径运行的 Agent 进程
function Get-SatsumaAgentProcess {
    param([string]$ExecutablePath)

    $fullPath = [IO.Path]::GetFullPath($ExecutablePath)
    return @(Get-CimInstance Win32_Process -Filter "Name = 'SatsumaVM.exe'" |
        Where-Object {
            if ($null -eq $_.ExecutablePath) {
                return $false
            }
            return [IO.Path]::GetFullPath($_.ExecutablePath) -eq $fullPath
        })
}

# 终止固定安装路径的旧 Agent，并确认文件不再被进程占用
function Stop-SatsumaAgentProcess {
    param([string]$ExecutablePath)

    foreach ($agentProcess in @(Get-SatsumaAgentProcess $ExecutablePath)) {
        Stop-Process -Id $agentProcess.ProcessId -Force -ErrorAction SilentlyContinue
    }

    $stopDeadline = [DateTime]::UtcNow.AddSeconds(10)
    do {
        if (@(Get-SatsumaAgentProcess $ExecutablePath).Count -eq 0) {
            return
        }
        Start-Sleep -Milliseconds 100
    } while ([DateTime]::UtcNow -lt $stopDeadline)
    throw '无法在超时前停止旧 SatsumaVM 进程。'
}

# 等待计划任务不再包含运行中或排队中的实例
function Wait-SatsumaTaskStopped {
    param([string]$TaskPath, [string]$TaskName)

    $stopDeadline = [DateTime]::UtcNow.AddSeconds(10)
    do {
        $task = Get-ScheduledTask `
            -TaskPath $TaskPath `
            -TaskName $TaskName `
            -ErrorAction SilentlyContinue
        if ($null -eq $task -or $task.State -notin @('Running', 'Queued')) {
            return
        }
        Start-Sleep -Milliseconds 100
    } while ([DateTime]::UtcNow -lt $stopDeadline)
    throw '无法在超时前停止旧 SatsumaVM 计划任务。'
}

# 为机器级安装路径设置最小可信 ACL
function Set-SatsumaPathAccessControl {
    param([string]$Path, [bool]$Container)

    if ($Container) {
        $security = New-Object Security.AccessControl.DirectorySecurity
        $inheritance = [Security.AccessControl.InheritanceFlags]'ContainerInherit, ObjectInherit'
        $propagation = [Security.AccessControl.PropagationFlags]::None
        $systemRule = New-Object Security.AccessControl.FileSystemAccessRule(
            $systemSid, 'FullControl', $inheritance, $propagation, 'Allow')
        $administratorsRule = New-Object Security.AccessControl.FileSystemAccessRule(
            $administratorsSid, 'FullControl', $inheritance, $propagation, 'Allow')
        $usersRule = New-Object Security.AccessControl.FileSystemAccessRule(
            $usersSid, 'ReadAndExecute', $inheritance, $propagation, 'Allow')
    } else {
        $security = New-Object Security.AccessControl.FileSecurity
        $systemRule = New-Object Security.AccessControl.FileSystemAccessRule(
            $systemSid, 'FullControl', 'Allow')
        $administratorsRule = New-Object Security.AccessControl.FileSystemAccessRule(
            $administratorsSid, 'FullControl', 'Allow')
        $usersRule = New-Object Security.AccessControl.FileSystemAccessRule(
            $usersSid, 'ReadAndExecute', 'Allow')
    }

    $security.SetAccessRuleProtection($true, $false)
    $security.SetOwner($administratorsSid)
    [void]$security.AddAccessRule($systemRule)
    [void]$security.AddAccessRule($administratorsRule)
    [void]$security.AddAccessRule($usersRule)
    Set-Acl -LiteralPath $Path -AclObject $security
}

# 拒绝重解析点并收紧整个安装树的已有权限
function Protect-SatsumaInstallTree {
    param([string]$Root)

    $installItems = @((Get-Item -LiteralPath $Root -Force)) +
        @(Get-ChildItem -LiteralPath $Root -Force -Recurse)
    foreach ($installItem in $installItems) {
        if (($installItem.Attributes -band [IO.FileAttributes]::ReparsePoint) -ne 0) {
            throw "安装目录不能包含重解析点：$($installItem.FullName)"
        }
    }
    foreach ($installItem in $installItems) {
        Set-SatsumaPathAccessControl $installItem.FullName $installItem.PSIsContainer
    }
}

# 共享目录中的部署文件
$bootstrapRoot = Join-Path $SharedRoot 'satsuma-bootstrap'
$sourceAgent = Join-Path $bootstrapRoot $AgentFileName
$sourceConfig = Join-Path $bootstrapRoot $ConfigFileName
foreach ($sourcePath in @($sourceAgent, $sourceConfig)) {
    if (-not (Test-Path -LiteralPath $sourcePath -PathType Leaf)) {
        throw "找不到部署文件：$sourcePath"
    }
}

# Guest 内固定使用受保护的本地机器级安装布局
$InstallRoot = [IO.Path]::GetFullPath($InstallRoot)
$installDriveRoot = [IO.Path]::GetPathRoot($InstallRoot)
$installRootLeaf = [IO.Path]::GetFileName($InstallRoot.TrimEnd('\', '/'))
if ($InstallRoot.TrimEnd('\', '/') -eq $installDriveRoot.TrimEnd('\', '/') -or
    $installRootLeaf -ne 'Satsuma') {
    throw 'InstallRoot 必须是固定磁盘中名为 Satsuma 的专用子目录。'
}
$installDrive = New-Object IO.DriveInfo($installDriveRoot)
if ($installDrive.DriveType -ne [IO.DriveType]::Fixed) {
    throw 'InstallRoot 必须位于 Guest 本地固定磁盘。'
}

$binRoot = Join-Path $InstallRoot 'bin'
$workRoot = Join-Path $InstallRoot 'work'
$targetAgent = Join-Path $binRoot 'SatsumaVM.exe'
$targetConfig = Join-Path $InstallRoot 'agent.json'
$targetScript = Join-Path $InstallRoot 'install-agent.ps1'
$taskPath = '\Satsuma\'
$taskName = 'SatsumaVM Agent'
$systemSid = New-Object Security.Principal.SecurityIdentifier('S-1-5-18')
$administratorsSid = New-Object Security.Principal.SecurityIdentifier('S-1-5-32-544')
$usersSid = New-Object Security.Principal.SecurityIdentifier('S-1-5-32-545')

# 防止两个安装脚本同时停止、替换同一 Agent
$installMutex = New-Object Threading.Mutex($false, 'Global\SatsumaVM-Install')
$ownsInstallMutex = $false
$stagingRoot = $null
$rollbackRoot = $null
$oldEnvironmentStopped = $false
$installSucceeded = $false
try {
    try {
        $ownsInstallMutex = $installMutex.WaitOne([TimeSpan]::FromSeconds(30))
    } catch [Threading.AbandonedMutexException] {
        $ownsInstallMutex = $true
    }
    if (-not $ownsInstallMutex) {
        throw '另一个 SatsumaVM 安装正在运行。'
    }

    New-Item -ItemType Directory -Force -Path $InstallRoot, $binRoot, $workRoot | Out-Null
    Protect-SatsumaInstallTree $InstallRoot

    # 停止旧环境前完成同盘暂存、哈希和配置预检
    $transactionId = [Guid]::NewGuid().ToString('N')
    $stagingRoot = Join-Path $InstallRoot ".install-$transactionId"
    $rollbackRoot = Join-Path $InstallRoot ".rollback-$transactionId"
    New-Item -ItemType Directory -Force -Path $stagingRoot, $rollbackRoot | Out-Null
    Set-SatsumaPathAccessControl $stagingRoot $true
    Set-SatsumaPathAccessControl $rollbackRoot $true
    $stagedAgent = Join-Path $stagingRoot 'SatsumaVM.exe'
    $stagedConfig = Join-Path $stagingRoot 'agent.json'
    $stagedScript = Join-Path $stagingRoot 'install-agent.ps1'
    Copy-Item -LiteralPath $sourceAgent -Destination $stagedAgent
    Copy-Item -LiteralPath $sourceConfig -Destination $stagedConfig
    Copy-Item -LiteralPath $MyInvocation.MyCommand.Path -Destination $stagedScript
    Unblock-File -LiteralPath $stagedAgent -ErrorAction SilentlyContinue
    Protect-SatsumaInstallTree $stagingRoot

    $sourceHash = (Get-FileHash -Algorithm SHA256 -LiteralPath $sourceAgent).Hash
    $stagedHash = (Get-FileHash -Algorithm SHA256 -LiteralPath $stagedAgent).Hash
    if ($sourceHash -ne $stagedHash) {
        throw 'SatsumaVM.exe 暂存后哈希不一致。'
    }
    $stagedConfigValue = Get-Content -Raw -Encoding UTF8 -LiteralPath $stagedConfig |
        ConvertFrom-Json -ErrorAction Stop
    if ([IO.Path]::GetFullPath($stagedConfigValue.local_work_root) -ne $workRoot) {
        throw "agent.json 的 local_work_root 必须是 $workRoot"
    }
    $presenceRoot = Join-Path $stagedConfigValue.shared_root 'agents'
    $presenceFile = Join-Path $presenceRoot ($stagedConfigValue.vm_id + '.json')
    & $stagedAgent --config $stagedConfig --validate-config
    if ($LASTEXITCODE -ne 0) {
        throw "SatsumaVM 配置预检失败，退出码：$LASTEXITCODE"
    }

    $existingTask = Get-ScheduledTask `
        -TaskPath $taskPath `
        -TaskName $taskName `
        -ErrorAction SilentlyContinue
    $previousTaskXml = $null
    $previousTaskWasRunning = $false
    if ($null -ne $existingTask) {
        $previousTaskXml = Export-ScheduledTask -TaskPath $taskPath -TaskName $taskName
        $previousTaskWasRunning = $existingTask.State -in @('Running', 'Queued')
    }
    $previousAgentWasRunning = @(Get-SatsumaAgentProcess $targetAgent).Count -gt 0

    $agentBackedUp = $false
    $configBackedUp = $false
    $backupAgent = Join-Path $rollbackRoot 'SatsumaVM.exe'
    $backupConfig = Join-Path $rollbackRoot 'agent.json'
    $newAgentInstalled = $false
    $newConfigInstalled = $false
    try {
        $oldEnvironmentStopped = $true
        if ($null -ne $existingTask) {
            Stop-ScheduledTask -InputObject $existingTask -ErrorAction Stop
            Wait-SatsumaTaskStopped $taskPath $taskName
        }
        Stop-SatsumaAgentProcess $targetAgent
        Remove-Item -Force -LiteralPath $presenceFile -ErrorAction SilentlyContinue

        if (Test-Path -LiteralPath $targetAgent) {
            Move-Item -LiteralPath $targetAgent -Destination $backupAgent
            $agentBackedUp = $true
        }
        if (Test-Path -LiteralPath $targetConfig) {
            Move-Item -LiteralPath $targetConfig -Destination $backupConfig
            $configBackedUp = $true
        }

        Move-Item -LiteralPath $stagedAgent -Destination $targetAgent
        $newAgentInstalled = $true
        Move-Item -LiteralPath $stagedConfig -Destination $targetConfig
        $newConfigInstalled = $true
        Set-SatsumaPathAccessControl $targetAgent $false
        Set-SatsumaPathAccessControl $targetConfig $false

        $targetHash = (Get-FileHash -Algorithm SHA256 -LiteralPath $targetAgent).Hash
        if ($sourceHash -ne $targetHash) {
            throw 'SatsumaVM.exe 切换后哈希不一致。'
        }

        Write-Host 'Satsuma VM Agent 已安装，正在注册并启动后台计划任务。'
        $installOutput = @(& $targetAgent --config $targetConfig --install-autostart)
        $agentExitCode = $LASTEXITCODE
        if ($agentExitCode -ne 0) {
            throw "SatsumaVM 计划任务安装失败，退出码：$agentExitCode"
        }
        $installResult = ($installOutput -join "`n") | ConvertFrom-Json -ErrorAction Stop
        $engineProcessId = [uint32]$installResult.engine_process_id
        if ($engineProcessId -eq 0) {
            throw 'SatsumaVM 未返回有效的计划任务引擎 ID。'
        }

        # 同时核对任务动作、任务状态、PID 和实际镜像路径
        $expectedArguments = '--config ' +
            (ConvertTo-WindowsCommandLineArgument $targetConfig) + ' --watch'
        $startDeadline = [DateTime]::UtcNow.AddSeconds(10)
        $verified = $false
        do {
            $registeredTask = Get-ScheduledTask `
                -TaskPath $taskPath `
                -TaskName $taskName `
                -ErrorAction Stop
            $registeredAction = @($registeredTask.Actions)[0]
            $presence = $null
            if (Test-Path -LiteralPath $presenceFile -PathType Leaf) {
                try {
                    $presence = Get-Content -Raw -Encoding UTF8 -LiteralPath $presenceFile |
                        ConvertFrom-Json -ErrorAction Stop
                } catch {
                    $presence = $null
                }
            }
            $presenceProcess = $null
            if ($null -ne $presence -and [uint32]$presence.process_id -gt 0) {
                $presenceProcess = Get-CimInstance `
                    Win32_Process `
                    -Filter "ProcessId = $([uint32]$presence.process_id)" `
                    -ErrorAction SilentlyContinue
            }
            $verified =
                $registeredTask.State -eq 'Running' -and
                $registeredAction.Execute -eq $targetAgent -and
                $registeredAction.Arguments -eq $expectedArguments -and
                $null -ne $presenceProcess -and
                $presenceProcess.ExecutablePath -eq $targetAgent -and
                $null -ne $presence -and
                $presence.vm_id -eq $stagedConfigValue.vm_id -and
                $presence.status -eq 'idle'
            if (-not $verified) {
                Start-Sleep -Milliseconds 200
            }
        } while (-not $verified -and [DateTime]::UtcNow -lt $startDeadline)
        if (-not $verified) {
            throw 'SatsumaVM 新计划任务未通过进程身份验证。'
        }

        try {
            Copy-Item -Force -LiteralPath $stagedScript -Destination $targetScript
            Set-SatsumaPathAccessControl $targetScript $false
        } catch {
            Write-Warning "Agent 已启动，但安装脚本副本更新失败：$_"
        }
        $installSucceeded = $true
        Write-Host 'Satsuma VM Agent 已在 SYSTEM 账户下持续运行，后续开机将自动启动。'
    } catch {
        $installFailure = $_
        Write-Warning "新 Agent 安装失败，正在恢复旧环境：$installFailure"
        $rollbackErrors = @()

        # 回滚过程逐项尽力执行，并保留原始安装错误
        try {
            $currentTask = Get-ScheduledTask `
                -TaskPath $taskPath `
                -TaskName $taskName `
                -ErrorAction SilentlyContinue
            if ($null -ne $currentTask) {
                Stop-ScheduledTask -InputObject $currentTask -ErrorAction SilentlyContinue
                Wait-SatsumaTaskStopped $taskPath $taskName
            }
            Stop-SatsumaAgentProcess $targetAgent
        } catch {
            Write-Warning "停止失败版本时发生错误：$_"
            $rollbackErrors += "停止失败版本失败：$_"
        }

        try {
            if ($newAgentInstalled -and (Test-Path -LiteralPath $targetAgent)) {
                Remove-Item -Force -LiteralPath $targetAgent
            }
            if ($newConfigInstalled -and (Test-Path -LiteralPath $targetConfig)) {
                Remove-Item -Force -LiteralPath $targetConfig
            }
            if ($agentBackedUp -and (Test-Path -LiteralPath $backupAgent)) {
                Move-Item -LiteralPath $backupAgent -Destination $targetAgent
            }
            if ($configBackedUp -and (Test-Path -LiteralPath $backupConfig)) {
                Move-Item -LiteralPath $backupConfig -Destination $targetConfig
            }
        } catch {
            $rollbackErrors += "文件回滚失败：$_"
        }

        $restoredByTask = $false
        if ($oldEnvironmentStopped -and $null -ne $previousTaskXml) {
            try {
                Register-ScheduledTask `
                    -TaskPath $taskPath `
                    -TaskName $taskName `
                    -Xml $previousTaskXml `
                    -Force | Out-Null
                if ($previousTaskWasRunning) {
                    Start-ScheduledTask -TaskPath $taskPath -TaskName $taskName
                    $restoredByTask = $true
                }
            } catch {
                $rollbackErrors += "计划任务回滚失败：$_"
            }
        }
        if ($oldEnvironmentStopped -and $previousAgentWasRunning -and -not $restoredByTask -and
            (Test-Path -LiteralPath $targetAgent) -and (Test-Path -LiteralPath $targetConfig)) {
            try {
                $restartArguments = '--config ' +
                    (ConvertTo-WindowsCommandLineArgument $targetConfig) + ' --watch'
                Start-Process `
                    -FilePath $targetAgent `
                    -ArgumentList $restartArguments `
                    -WorkingDirectory $binRoot `
                    -WindowStyle Hidden | Out-Null
            } catch {
                $rollbackErrors += "旧 Agent 重启失败：$_"
            }
        }
        if ($rollbackErrors.Count -gt 0) {
            throw "安装失败：$installFailure；回滚失败：$($rollbackErrors -join '；')"
        }
        throw $installFailure
    } finally {
        if (Test-Path -LiteralPath $stagingRoot) {
            Remove-Item -Force -Recurse -LiteralPath $stagingRoot
        }
        if ($installSucceeded -and (Test-Path -LiteralPath $rollbackRoot)) {
            Remove-Item -Force -Recurse -LiteralPath $rollbackRoot
        }
    }
} finally {
    if ($null -ne $stagingRoot -and (Test-Path -LiteralPath $stagingRoot)) {
        Remove-Item -Force -Recurse -LiteralPath $stagingRoot
    }
    if ($null -ne $rollbackRoot -and
        ($installSucceeded -or -not $oldEnvironmentStopped) -and
        (Test-Path -LiteralPath $rollbackRoot)) {
        Remove-Item -Force -Recurse -LiteralPath $rollbackRoot
    }
    if ($ownsInstallMutex) {
        [void]$installMutex.ReleaseMutex()
    }
    $installMutex.Dispose()
}
